/**/spinnaker_node:
  ros__parameters:
    stereo:
      topic: "stereo" #TODO: renmae
      frame: "stereo_frame"
      left:
        serial: "14490542"
        hardware_trigger: true
      right:
        serial: "15662023"
        hardware_trigger: false
